### ISSUE TITLE
alot. of errors.

### ISSUE THREAD

**Issue by huhvzi** [NightfallGT/Discord-Account-Generator#106]
Traceback (most recent call last):
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001FD2EF88B10>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.gmailnator.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FD2EF88B10>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\discordgenerator.py", line 380, in <module>
    main()
  File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\discordgenerator.py", line 377, in main
    worker()
  File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\discordgenerator.py", line 232, in worker
    g = GmailnatorGet()
  File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\src\api.py", line 87, in __init__
    super().__init__()
  File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\src\api.py", line 28, in __init__
    self.csrf_token = self.__get_csrf()
  File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\src\api.py", line 31, in __get_csrf
    response = self.s.get(self.BASE_URL)
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.gmailnator.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FD2EF88B10>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

**Comment by DBGx64** [comment]
> Traceback (most recent call last): File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn conn = connection.create_connection( File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 72, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM): File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno 11002] getaddrinfo failed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request self._validate_conn(conn) File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn conn.connect() File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 358, in connect self.sock = conn = self._new_conn() File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001FD2EF88B10>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 489, in send resp = conn.urlopen( File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen retries = retries.increment( File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.gmailnator.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FD2EF88B10>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\discordgenerator.py", line 380, in main() File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\discordgenerator.py", line 377, in main worker() File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\discordgenerator.py", line 232, in worker g = GmailnatorGet() File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\src\api.py", line 87, in **init** super().**init**() File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\src\api.py", line 28, in **init** self.csrf_token = self.__get_csrf() File "C:\Users\vaibh\Desktop\Python Projects\dislock\gen\src\api.py", line 31, in __get_csrf response = self.s.get(self.BASE_URL) File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 600, in get return self.request("GET", url, **kwargs) File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "C:\Users\vaibh\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 565, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.gmailnator.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FD2EF88B10>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

have you found a solution?
