### ISSUE TITLE
ChromeDriver only supports Chrome version 89

### ISSUE THREAD

**Issue by DevAmiyo** [NightfallGT/Discord-Account-Generator#36]
~`Traceback (most recent call last):
  File "E:\Github\Discord-Account-Generator-main\discordgenerator.py", line 382, in <module>
    main()
  File "E:\Github\Discord-Account-Generator-main\discordgenerator.py", line 379, in main
    worker()
  File "E:\Github\Discord-Account-Generator-main\discordgenerator.py", line 257, in worker
    d = DiscordGen(new_email, username, password)
  File "E:\Github\Discord-Account-Generator-main\discordgenerator.py", line 67, in __init__
    self.driver = webdriver.Chrome(options=options, executable_path=r"chromedriver.exe")
  File "C:\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 53, in __new__
    instance.__init__(*args, **kwargs)
  File "C:\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 89
Current browser version is 91.0.4472.124 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe`~

================ F I X E D ===================

**Comment by bytixo** [comment]
try to read the readme before submitting an issue, you need this version of the webdriver : 91.0.4472.124

**Comment by epyklion** [comment]
there's no webdriver for 91.0.4472.124

**Comment by bytixo** [comment]
https://chromedriver.chromium.org/downloads plz learn to read idk common sense gl
