### ISSUE TITLE
Chromedriver & cloudflare issue

### ISSUE THREAD

**Issue by FeelsBadMan1** [NightfallGT/Discord-Account-Generator#59]
Hey, i noticed after running this script on repl.it what is based on linux that this long wired issue happens and im not sure how im able to solve this:
```
sh: 1: title: not found
sh: 1: Proxy:: not found
sh: 1: Threading:: not found
[!] Scraping email. 
[*] Scraped <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>

<title>Please Wait... | Cloudflare</title>
  
<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->


  
    <script type="text/javascript">
    //<![CDATA[
    (function(){
      window._cf_chl_opt={
        cvId: "2",
        cType: "managed",
        cNounce: "72941",
        cRay: "68c06f74dc922860",
        cHash: "b1cb1a510d534bf",
        cFPWv: "g",
        cTTimeMs: "1000",
        cLt: "n",
        cRq: {
          ru: "aHR0cHM6Ly93d3cuZ21haWxuYXRvci5jb20vaW5kZXgvaW5kZXhxdWVyeQ==",
          ra: "cHl0aG9uLXJlcXVlc3RzLzIuMjUuMQ==",
          rm: "UE9TVA==",
          d: "b6p7ohOwToWoNvZi+h9yuwLYDCpP4/FuXzcYpjT2WvsY+VyQyOIxEpF+MVDCcXscTC/H8zMwjL2zcwK24zInD9LHPaPFpQpcCQuPLTfGeNMoXi2JEnvwVFjlwOfFNT9shFTiY5+GTKnyMCL4rxu+I/f02n07bNV7qPAdM7UFOqiYvrOKwjpyEzE20Og4usrBQI4S8Kp4BkBUn8o8O0R//tHnAlF0+8RnMa8NyQd8hk6XGZRQWsdh4pbbstBHiN12T3WNv8o0vmPxjKOnzJ9B3RYKQSQ+MxXIMYTl1JdgvMqdU1SDj/FtVRHdtrOMJLtvaLVYrBR53IaNVXbDdHh7m60VrrhUhbyLHt2+hHifjeSuNw+MkdDU4H4rY4wyW/YRE/H1ptp2O8LUV8nbgbq2hbVlvNma7cE4njCpNALAW427Jk8ajjwNYmjdMYU4G+4+z6vP/GlK9y6QMzirbTHwIu3Ln0JtG5zDaSY3n133GtkUCZVUqOlgMMotEvwlr/uWO7t4px0hzrcwMJBmQ7mD2k2cfd0xGfid46/eK5NNV09gpXgGMFwVp4sCKdrJ5SVG05YJ+dCfakXk61Ng6vUzHTHLG8gxPfl0SpzRb8eddsd6jsVk9kKqC5nD9XnQuh8IrnRXtAA1FMmr1akZhs7xnd4qvNNpas4TSp61Ab7ObVJdj2VIwYW8K8bMc1RRm/tqnm3ijUz6G6O4J8olLbe6E5UYgyOvZH40nkKXz6/s6ihwdQdAjvyF94RhDwoYpt50dYnVIXkY4bb3lJsr4DixNANoY0rs7yFdi2L9HfdRSPjzyzBW9NQSq/VnEj5vWEybmXynsdtF5NC+U+0OllI0E7nen5jwHZjevEInh6Ybw/8yozAenLkTJ1zE7727utAuVkvwhR5f6k0rhm+8QwGP4Q==",
          t: "MTYzMTE5MDcwNS40MjQwMDA=",
          m: "mpnb9XYwfQ9syasjfF0pClGD+n5QBeUcncbCVhJY0eI=",
          i1: "nU+NGTIVTeS05mggR+MaxQ==",
          i2: "OFspNi4bsKtpafmcbEqfGQ==",
          zh: "S+QwFpXzjsdm24BVqWd33gTZev8pfgyyDt8L+uwnOoY=",
          uh: "5GU+jYv2xJ+bCaE/ARmi/DORbiS/v56CW7E0TH4XWQk=",
          hh: "9xOUqkjebyr4GBfD7RMAVvEVDbOQRcR7P2LZyGTHmxs=",
        }
      };
    }());
    //]]>
    </script>
  

<style type="text/css">
  #cf-wrapper #spinner {width:69px; margin:  auto;}
  #cf-wrapper #cf-please-wait{text-align:center}
  .attribution {margin-top: 32px;}
  .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
  #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
  #cf-hcaptcha-container { text-align:center;}
  #cf-hcaptcha-container iframe { display: inline-block;}
  @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-wrapper #cf-bubbles { width:69px; }
  @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
  #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
  #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
  #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
</style>
</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
      
        <h1 data-translate="managed_challenge_headline">Please wait...</h1>
        <h2 class="cf-subheadline"><span data-translate="managed_checking_msg">We are checking your browser...</span> www.gmailnator.com</h2>
      
      </div>
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form managed-form" id="challenge-form" action="/index/indexquery?__cf_chl_managed_tk__=pmd_iFH4iKg5xni9VbwuALDE0N4q_lquY84RYJVBqtshsCE-1631190705-0-gqNtZGzNAtCjcnBszQel" method="POST" enctype="application/x-www-form-urlencoded">
  
    <div id='cf-please-wait'>
      <div id='spinner'>
        <div id="cf-bubbles">
            <div class="bubbles"></div>
            <div class="bubbles"></div>
            <div class="bubbles"></div>
        </div>
      </div>
      <p data-translate="please_wait" id="cf-spinner-please-wait">Please stand by, while we are checking your browser...</p>
      <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting...</p>
      </div>
  
  <input type="hidden" name="md" value="lNL.ZZY.HEZ.z7rCTPNuGNTxUTRfvnt2vohEgJFsgq4-1631190705-0-AYrZQP0HDg0DW_8j1erF7yAVKrkE-lNBLdAI92jc8QNRLHVMv1cq0G_R3lr-QLwRa3eRvibAdqhiUediI1i4M7ZC9NitT_JwSV1mroBuxVdPcVaj_qDWm2La1IEm6rNOPSLEdsFMokqwW943v72z084bAZ00QfM3uoC3is8kEgbCUgKLu-sT62TzmdVur-6cV1P67TQjulLClVpK8HX0ihLkOqxaPSqVvQJn5-8DuK1PC7pKyUAy9T4mRGji3nZtujJzGeKOo6W372wO0ExYQHdsvnuEd8Ja8LVgyoAEPCE7Gwv-UvPtRgO40Gg207zqxZqUcXbj3DhjucW6Xvo6nYStVttVedVFXOFAYfS1DoTJ3fUyg9j4sN8YMoKRVV_dDWbUi0BKTG-FtfPmHXNoCVJ2iPzmnu7gtU7TK_ToxdqrFv5A8LjtkRIqZxgjxSpvMLuF3y0eV0cX7sAwTEJ7XqsGOesHle0cBVNiY-Z2hUzWVnkhGTOxFNWvQFOwLsy7BWGRqkvpDQ3w6zr1FVJhlaHq317WiFDtFUxdeQMmPD3PIv2zveli_O4MDD2n3pyQulRRNJSIJOL4rhRu27D-yj60TtY5Y69B4Y_pZVr1hk2b3d-Q5jgSIPbi0dtxZ-GMGZD2VqcwJToZgWWYmab_5OY" />
  <input type="hidden" name="r" value="fuFvhBpcU0PPArTw4R3XagBBdBiNCgQrWSePmCVDpII-1631190705-0-Ad/Q7UmwuwkEX+j+zsb5JyitgT6Nv+uT8dgrFZAua8ZiMA8sPy9PhlRAMbtE9UWH6lfNiMate8nRCoj+Ld+nRpOmDC+Cij890JTXD5eKskQrZsWUaBDevQYZpegWxFOpjI3mO9vFi+Z2Kq0OU0wA2NV700+L4pIhDby+YU0l2ItFeUK5iw6tWGFhYWCr5iKlCMFhLKbqMHpgSAytREiI1Fw6lUgaj09vl4gAchA6aRrhdogNsmJbaye55cLeALJK3c75xc8MxFkTqf7hw+z4nxjz1xX4EwPAFGSdpACwpa6zwpv+tQCsT8vsF723xnbHO5nfmljFLoNDbzx1ruGS/0rGwMROiQ+QrF2du5VNGsrNxd7UWC7Ev09YsWOk3LhNVUNFGDsUZ9J5hQmjBIjAzPNTNFzZmHs2iW2HjSuCa2alSc/rw+y4GYpJCXTKjDHO0ixo7AZ/reUeOGDJNvk9NPlFfCYwzmHlVqjuSbJFgLSmEezbSdT2/fKa1AtVZpf+Z9UyjV996kUQwAu+rfKmIQ7x8aik2YvVzP4KPGf+hVsygq4nY/3DMLfe5W7sqZkQmCMWikJKIj9M1KZJPNcs9BI5Dh+6Ebt3sA0DX7mbLyhdkeJjmHgNajgtJfTnj2qozRrJlYC4wCBSHRmIGQ98zLhNmsRKLa39xlylxIyWueSCcCf0ESCJInbrJk6zJk9HCFUfrLKzySmVmQLnChB1Xl8QnbvEtQJOBNOxylOL3f4qFKySlm1GZ4RVUGMchGdK8dau/TZrcCqCI4nyyl4dlLVKFbTkli92Mf5acJGc+X2mk+Ud6tm2YymjVAdWYIlMPH5Dw1b64CcodLkoXDYaRIghVPxB7ds4sI+xDj/xBFI5tjYVeFO/6wvNdp9o45/igdlh1eoiYWztp2S5xk77fI7n2cdnCD7xVlDHtlJ02zfu3nQPGvGytpT33j3+rHupR7JMm3k12+PI5PZ2gSJYbYiA50rV+cBEKdZWXsSeQvVIapsgK3Ei0oX+VpINuTj/kBIkZXRc/fGk+Q8S1SgoF5ucH3hJZmA78tr4fNisWd8l1FaOuNXvfUg4eEH/FkiF40joD5lwrIywhsg9CCQ1Yps8URUw5zON99YI1p3uFBGmAqvsJgI5BVculGijZpzmvrfTHepSvIpGGHvh/jzZSSdVH6IJGbhGErMq8bzqKdcGMsjGFPLArMajq0Pl4+DJKzQ+cExr3Da7TwXzdsuRXyu7ufeoVbEiHhxfWv6Pw7FRDVdMhSVTgcMO8q0aAe4C/TVYauflBeSjeHwWurO529m3oqcl4EDxZnLGrxewH1pfpkBzxgrt+BfoHx3ha09A+dAJI2MTmBcwtVT6IORFtMe+KVDBLMzQqBo+4rvjfeGmfQxQ6/V6UFgVkdKgYTz057t+HbzExkDReDam1F0l3IjZWCiy8gm0lb/gP+sbh+/6+V1wgCp3TunWux7vxJR+2qYOFvB/zD0kR99p0a5LtztQnmp4ANNnJS6mQmqvLC8KR/4Nfb8LQ9KY+T78qEGRECh1lemtwWbped7L1SJmEI8RGmxrdsQN/iLj55lc4ddU44GFUFhGo3JaP8RltEqs7U90HpfLSoHRwwLftFA7GmFWd3yhlfWvCu79/uslsG2EADLcUUsk5QwOdv809LO6cDIm+T7Q4kHHR2FPkzgqEu/SI0wPpCoW/PvbHM65DvMvNwKKNPphxXzyoyQpW59MHu5dQVRakyHRoDmdxmAeGsDtVThGQDT9SExwyaFn8t17fgur9tS+8r3GSKm5b+aITzjiWwhGg+zjXZSKv7It2XzQundZEK0tfnK6ze0GkUvzzY0P9KJbhX1RRgn7IoVBljJ/YMhoHyQpzLeALJMW7Ja14UVG36K0xGaYeGvgxbD2">
  <input type="hidden" name="cf_captcha_kind" value="h">
  <input type="hidden" name="vc" value="282fe438f057032ea123d2334b967aa2">
  
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
  <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
  <script type="text/javascript">
  //<![CDATA[
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
      b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
      b(function(){
        var cookiesEnabled=(navigator.cookieEnabled)? true : false;
        if(!cookiesEnabled){
          var q = document.getElementById('no-cookie-warning');q.style.display = 'block';
        }
      });
  //]]>
  </script>
  <div id="trk_captcha_js" style="background-image:url('/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=68c06f74dc922860')"></div>
</form>
  
  <script type="text/javascript">
    //<![CDATA[
    (function(){
        var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
        var trkjs = isIE ? new Image() : document.createElement('img');
        trkjs.setAttribute("src", "/cdn-cgi/images/trace/managed/js/transparent.gif?ray=68c06f74dc922860");
        trkjs.id = "trk_managed_js";
        trkjs.setAttribute("alt", "");
        document.body.appendChild(trkjs);
        var cpo=document.createElement('script');
        cpo.type='text/javascript';
        cpo.src="/cdn-cgi/challenge-platform/h/g/orchestrate/managed/v1?ray=68c06f74dc922860";
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
    //]]>
    </script>
  


              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">
              
                <span class="cf-no-screenshot"></span>
              
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
            <a href="https://thepaulrobinson.com/printing.php?doc_id=4" style="position: absolute; top: -250px; left: -250px;"></a>
            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
            

            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
            
              
            
          </div>
        </div>
      </div>
      

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">68c06f74dc922860</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 34.69.145.187</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>


</body>
</html>

Traceback (most recent call last):
  File "main.py", line 382, in <module>
    main()
  File "main.py", line 379, in main
    worker()    
  File "main.py", line 257, in worker
    d = DiscordGen(new_email, username, password)
  File "main.py", line 67, in __init__
    self.driver = webdriver.Chrome(options=options)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 57, in __new__
    instance.__init__(*args, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 339, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 400, in execute
    self.error_handler.check_response(response)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 236, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5598e769d583 <unknown>
#1 0x5598e7411a38 <unknown>
#2 0x5598e7434923 <unknown>
#3 0x5598e74304df <unknown>
#4 0x5598e746a1e2 <unknown>
#5 0x5598e7464643 <unknown>
#6 0x5598e743ab94 <unknown>
#7 0x5598e743bb85 <unknown>
#8 0x5598e76cdc6e <unknown>
#9 0x5598e76e3975 <unknown>
#10 0x5598e76cebc5 <unknown>
#11 0x5598e76e4fb5 <unknown>
#12 0x5598e76c384b <unknown>
#13 0x5598e7700248 <unknown>
#14 0x5598e77003c8 <unknown>
#15 0x5598e771a73d <unknown>
#16 0x7f7826d896db start_thread

 
```

**Comment by EOSonGameboy** [comment]
me too sorry

**Comment by FeelsBadMan1** [comment]
I now implemented a few of the code in a own project however now when it try to agree the ToS it only wrap the checkbox around with a blue border... i also tried to use pyautogui to make it more humanlike but it still was the same. if i click manually it works

**Comment by BallisticOK** [comment]
how did you get it working
