### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by AlexCasanova** [NightfallGT/Discord-Account-Generator#68]
After scraping email, the script crashes as mentionned in the previous issues

**Comment by eltrevii** [comment]
like this?
```py
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 600, in urlopen
  File "urllib3\connectionpool.py", line 343, in _make_request
  File "urllib3\connectionpool.py", line 839, in _validate_conn
  File "urllib3\connection.py", line 344, in connect
  File "urllib3\util\ssl_.py", line 345, in ssl_wrap_socket
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 638, in urlopen
  File "urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.gmailnator.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "discordgenerator.py", line 382, in <module>
  File "discordgenerator.py", line 375, in main
  File "discordgenerator.py", line 234, in worker
  File "src\api.py", line 87, in __init__
    super().__init__()
  File "src\api.py", line 28, in __init__
    self.csrf_token = self.__get_csrf()
  File "src\api.py", line 31, in __get_csrf
    response = self.s.get(self.BASE_URL)
  File "requests\sessions.py", line 555, in get
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.gmailnator.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')))
[9396] Failed to execute script discordgenerator
```
