### ISSUE TITLE
Error please help

### ISSUE THREAD

**Issue by Khaos11010** [NightfallGT/Discord-Account-Generator#71]
I keep getting this error this is not the full thing put all i could get before the program closed its self how do i fix???

[*] Proxy used 93.183.214.121:8080
[!] Scraping email.
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 600, in urlopen
  File "urllib3\connectionpool.py", line 343, in _make_request
  File "urllib3\connectionpool.py", line 839, in _validate_conn
  File "urllib3\connection.py", line 344, in connect
  File "urllib3\util\ssl_.py", line 345, in ssl_wrap_socket
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 638, in urlopen
  File "urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.gmailnator.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')))

**Comment by eltrevii** [comment]
i have same problem

**Comment by Aethese** [comment]
solution in #72
