### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by d2adric** [NightfallGT/Discord-Account-Generator#76]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Database\Discord-Account-Generator-main\discordgenerator.py", line 1, in <module>
    import undetected_chromedriver as uc
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\undetected_chromedriver\__init__.py", line 31, in <module>
    from . import v2
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\undetected_chromedriver\v2.py", line 21, in <module>
    from .cdp import CDP
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\undetected_chromedriver\cdp.py", line 6, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.240.0_x64__qbz5n2kfra8p0\lib\collections\__init__.py)

i download all the extensions

**Comment by FLAREASTIC** [comment]
sex
