### ISSUE TITLE
can anyone help me please?

### ISSUE THREAD

**Issue by Archard1337** [NightfallGT/Discord-Account-Generator#88]
Traceback (most recent call last):
  File "C:\Users\archw\Desktop\Discord-Account-Generator-main\Discord-Account-Generator-main\discordgenerator.py", line 3, in <module>
    driver = webdriver.Chrome()
  File "C:\Users\archw\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\archw\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\archw\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\archw\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\archw\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\archw\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 89
Current browser version is 97.0.4692.71 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x00CFE7D3+124883]
        Ordinal0 [0x00CFE7B1+124849]
        GetHandleVerifier [0x00F48688+193832]
        GetHandleVerifier [0x00F63AC5+305509]
        GetHandleVerifier [0x00F6021B+291003]
        GetHandleVerifier [0x00F5E0AC+282444]
        GetHandleVerifier [0x00F84A90+440624]
        GetHandleVerifier [0x00F847FC+439964]
        GetHandleVerifier [0x00F8154B+426987]
        GetHandleVerifier [0x00F64FFD+310941]
        GetHandleVerifier [0x00F65D8E+314414]
        GetHandleVerifier [0x00F65D19+314297]
        GetHandleVerifier [0x010231EC+1089676]
        GetHandleVerifier [0x010217C9+1082985]
        GetHandleVerifier [0x010213A3+1081923]
        GetHandleVerifier [0x0111D9FD+2115741]
        Ordinal0 [0x00E4B82E+1488942]
        Ordinal0 [0x00DE5A7D+1071741]
        Ordinal0 [0x00DE559B+1070491]
        Ordinal0 [0x00DE54B1+1070257]
        Ordinal0 [0x00E1FF53+1310547]
        BaseThreadInitThunk [0x77176739+25]
        RtlGetFullPathName_UEx [0x774D8AFF+1215]
        RtlGetFullPathName_UEx [0x774D8ACD+1165]

**Comment by arin2115** [comment]
This gen doesn't work and won't work anymore. There is no free generator.
