### ISSUE TITLE
g = GmailnatorGet() error

### ISSUE THREAD

**Issue by nicholaslz** [NightfallGT/Discord-Account-Generator#99]
I kept getting this error when I tried to run the program and it seems to me that many people have this too:
`Traceback (most recent call last):
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\nicho\AppData\Local\Programs\Python\Python39\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001FE1A7DA460>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.gmailnator.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FE1A7DA460>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\discordgenerator.py", line 355, in <module>
    worker()
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\discordgenerator.py", line 206, in worker
    g = GmailnatorGet()
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\src\api.py", line 86, in __init__
    super().__init__()
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\src\api.py", line 28, in __init__
    self.csrf_token = self.__get_csrf()
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\src\api.py", line 31, in __get_csrf
    response = self.s.get(self.BASE_URL)
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\nicho\Desktop\Programming\Python\HACK\satan\accgen\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.gmailnator.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FE1A7DA460>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))`

Can anyone tell me what's happening?

**Comment by Roboticol** [comment]
getting the same problem, have you found a fix to it?

**Comment by luxkatana** [comment]
Having the same problem.
